[package]
edition = "2021"
name = "tonbo-python"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
fusio = { git = "https://github.com/tonbo-io/fusio.git", rev = "af66ff6cb9aaab3b6a85a3481037b13ff677fc31", package = "fusio", version = "0.3.1", features = [
    "aws",
    "tokio",
] }
fusio-dispatch = { git = "https://github.com/tonbo-io/fusio.git", rev = "af66ff6cb9aaab3b6a85a3481037b13ff677fc31", package = "fusio-dispatch", version = "0.2.0", features = [
    "aws",
    "tokio",
] }
futures = { version = "0.3" }
pyo3 = { version = "0.21.2", features = [
    "abi3",
    "abi3-py310",
    "extension-module",
] }
pyo3-asyncio = { package = "pyo3-asyncio-0-21", version = "0.21", features = [
    "tokio-runtime",
] }
tokio = { version = "1", features = ["rt-multi-thread"] }
tonbo = { version = "0.2.0", path = "../../" }
